version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    image: kavindu128/employee-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employeeDirectory
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    image: kavindu128/employee-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
